
networks:
  backend:
    driver: bridge

services:
  app:
    image: sftp-app
    container_name: sftp_camel
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend

  sqlite-container:
    image: alpine:latest
    volumes:
      - ./database:/data
    #command: sh -c "apk --no-cache add sqlite && cp /data/initial-db.sqlite /data/db.sqlite && sqlite3 /data/db.sqlite < /data/init.sql && tail -f /dev/null"
    container_name: sqlite-container

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - sqlite_data:/data/db
    container_name: sqlitebrowser
  sftp:
    image: atmoz/sftp
    container_name: atmoz_sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data:/home/foo/upload
    networks:
        - backend
    command: foo:pass:1001

  filezilla:
    image: jlesage/filezilla
    ports:
      - "5800:5800"
    volumes:
      - filezilla-config:/config:rw
      - filezilla-storage:/storage:rw
    networks:
      - backend

volumes:
  sqlite_data:
  filezilla-config:
  filezilla-storage: